name: blog

services:
  pre-process:
    image: busybox
    volumes:
      - server-secrets:/secrets
    # 另一个容器预处理卷的权限问题
    # -R 表示递归
    entrypoint: chown -R 1654 /secrets

  blog-server:
    image: littletoxic/blog-server
    ports:
      - "5000:8080/tcp"
    devices:
      - "/dev/i2c-0:/dev/i2c-0"
      - "/dev/i2c-1:/dev/i2c-1"
    restart: unless-stopped
    # non-root 容器中获取足够权限访问设备
    user: '1654:994'
    volumes:
      - server-secrets:/app/secrets
    depends_on:
      pre-process:
        condition: service_completed_successfully

volumes:
  server-secrets: